# Site settings
email: isc.suriyaa@gmail.com
description: 
url: "http://isc-host.github.io/isc-services.com/" # the base hostname & protocol for your site
repository: https://github.com/iSC-Host/isc-services.com
